version: '3.6'
services:
  app:
    build: .docker/apachephp
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/project/poc-messenger
      - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
    restart: always
    env_file:
      - .env
    depends_on:
      - dbmysql

  dbmysql:
    build:
      context: .docker/mysql
      args:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_PORT: ${DB_PORT}
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TIMEZONE:-Europe/Paris}
    ports:
      - "3306"

  mailer:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
