version: '3.6'
services:
  app:
    build: ../apachephp
    ports:
      - "80"
    volumes:
      - ../../:/var/www/project/poc-messenger
      - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
    restart: unless-stopped
    depends_on:
      - dbmysql

  dbmysql:
    build:
      context: ../mysql
      args:
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
        MYSQL_ROOT_PASSWORD: ${DB_PASS}
        MYSQL_PORT: ${DB_PORT}
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${TIMEZONE:-Europe/Paris}
    restart: unless-stopped
    ports:
      - "3306"
